; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.3.0
; MAIN_PROGRAM_V104.inc
; 10:24:50 PM Friday, August 04, 2023
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "MAIN_PROGRAM_20170905.MCU" 
#include "..\BS83B04A_LIBV413\BS83B04A_LIBV413.aex" 
#define                                
#define EXTEND_FUNCTION_1A_INITIAL     _BS83B04A_LIBV413_INITIAL
#define EXTEND_FUNCTION_1A             _BS83B04A_LIBV413
#include "..\USER_PROGRAM\USER_PROGRAM.aex" 
#define                                
#define EXTEND_FUNCTION_1B_INITIAL     _USER_PROGRAM_INITIAL
#define EXTEND_FUNCTION_1B             _USER_PROGRAM
