; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.3.0
; USER_PROGRAM.inc
; 10:24:50 PM Friday, August 04, 2023
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "..\BS83B04A_LIBV413\BS83B04A_LIBV413.aex" 
#include "..\MAIN_PROGRAM_V104\MAIN_PROGRAM_V104.aex" 
